name: Now
on:
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set git identity
        run: |-
          git config user.name "Automation"
          git config user.email "github-actions@github.com"
      - name: Touch
        run: date > ./now
      - run: git add ./now
      - name: Commit and push changes (if any)
        run: 'git add . && git commit -m "chore: update now" && git push origin HEAD:${{ github.event.pull_request.head.ref }}'
      - if: ${{ github.repository == github.event.pull_request.head.repo.full_name }}
        name: Update status check
        run: gh api -X POST /repos/${{ github.event.pull_request.head.repo.full_name
          }}/check-runs -F name="build" -F head_sha="$(git rev-parse HEAD)" -F
          status="completed" -F conclusion="success"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
