name: test
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::boom\n```this is great```Can I use *markdown* here?\nOH NO!\n## Heading 2\nYes!"
