name: test
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  self-mutation:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - run: hello world
